---
apiVersion: v1
kind: Secret
metadata:
  name: cilium-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: cilium
  url: https://helm.cilium.io
  enableOCI: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: longhorn
  url: https://charts.longhorn.io
  enableOCI: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: kubevirt-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: kubevirt
  url: https://kubevirt.github.io/kubevirt-charts
  enableOCI: "false"