---
# Note: This Application adopts the Cilium installation from install-cilium.sh
# It does NOT reinstall Cilium, but manages it via GitOps going forward
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    # This app should be created AFTER Cilium is installed via install-cilium.sh
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.16.5  # Latest stable as of 2026-01
    helm:
      values: |
        # IPAM Configuration
        ipam:
          mode: kubernetes

        # eBPF kube-proxy replacement
        kubeProxyReplacement: true
        k8sServiceHost: 10.0.100.111  # VIP address
        k8sServicePort: 6443

        # BGP Control Plane (for advanced routing)
        bgpControlPlane:
          enabled: true

        # Load Balancer Mode
        loadBalancer:
          mode: hybrid
          acceleration: native

        # Native routing (no overlay)
        routingMode: native
        autoDirectNodeRoutes: true
        ipv4NativeRoutingCIDR: 10.1.0.0/16
        enableIPv4Masquerade: true
        enableIPv6Masquerade: false

        # eBPF Masquerading
        bpf:
          masquerade: true
          tproxy: true

        # Hubble (Network Observability)
        hubble:
          enabled: true

          relay:
            enabled: true
            replicas: 1

          ui:
            enabled: true
            replicas: 1
            ingress:
              enabled: false  # Configure via Gateway API later

          metrics:
            enabled:
              - dns:query
              - drop
              - tcp
              - flow
              - icmp
              - http
            serviceMonitor:
              enabled: false  # Enable if Prometheus is installed
            dashboards:
              enabled: false  # Enable if Grafana is installed

        # Gateway API Support (for L7 policies)
        gatewayAPI:
          enabled: true

        # Enable IPv4 (IPv6 disabled for this setup)
        ipv4:
          enabled: true
        ipv6:
          enabled: false

        # Operator configuration
        operator:
          replicas: 1
          prometheus:
            enabled: false  # Enable if Prometheus is installed

        # Prometheus metrics
        prometheus:
          enabled: false  # Enable if Prometheus is installed

        # CNI Configuration
        cni:
          install: true
          exclusive: true

        # Bandwidth Manager (for rate limiting)
        bandwidthManager:
          enabled: true
          bbr: true

        # Host firewall
        hostFirewall:
          enabled: true

        # Encryption (disabled for performance, enable if needed)
        encryption:
          enabled: false
          type: wireguard

        # Local Redirect Policy (for efficient local traffic)
        localRedirectPolicy: true

        # KubeVirt support (hostPort mapping for VMs)
        hostPort:
          enabled: true

        # Multus support (secondary network interfaces)
        cni:
          chainingMode: none
          customConf: false

        # Security
        policyEnforcementMode: default

        # Resource limits
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 512Mi

        # Node selector (run on all nodes)
        nodeSelector:
          kubernetes.io/os: linux

        # Tolerate all taints (run on control plane too)
        tolerations:
          - operator: Exists

        # Pod disruption budget
        pdb:
          enabled: false  # Disable for 3-node cluster

        # Rollout strategy
        rolloutMaxUnavailable: 1

        # Debug (disable in production)
        debug:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true  # Don't redeploy existing resources
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences between Helm-installed and ArgoCD-managed resources
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/metadata/annotations/container.apparmor.security.beta.kubernetes.io~1cilium-agent
        - /spec/template/metadata/annotations
        - /metadata/labels/app.kubernetes.io~1managed-by
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /metadata/annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
        - /metadata/labels/app.kubernetes.io~1managed-by
