---
# Cilium CNI - ArgoCD Application
#
# IMPORTANT: This Application adopts the Cilium installation from Talos inline manifests
# Cilium is deployed automatically at bootstrap time via inline manifests in Talos config
# This ArgoCD app adopts it for GitOps management (NO redeployment!)
#
# The values below MUST match cilium-values.yaml exactly to prevent ArgoCD from
# attempting to update/redeploy Cilium.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    # Note: Cilium is already running when this App is created
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.18.6  # Must match version in inline manifests
    helm:
      # Values from cilium-values.yaml (synchronized)
      values: |
        # IPAM Configuration
        ipam:
          mode: kubernetes

        # eBPF kube-proxy replacement
        kubeProxyReplacement: true
        k8sServiceHost: localhost  # Talos KubePrism
        k8sServicePort: 7445       # Talos KubePrism port

        # Talos-specific settings
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE

        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup

        # BGP Control Plane
        bgpControlPlane:
          enabled: true

        # Load Balancer
        loadBalancer:
          mode: hybrid
          acceleration: native

        # Native routing
        routingMode: native
        autoDirectNodeRoutes: true
        ipv4NativeRoutingCIDR: 10.1.0.0/16
        enableIPv4Masquerade: true
        enableIPv6Masquerade: false

        # eBPF Masquerading
        bpf:
          masquerade: true
          tproxy: true

        # Endpoint routes
        endpointRoutes:
          enabled: true

        # Hubble (Observability)
        hubble:
          enabled: true
          relay:
            enabled: true
            replicas: 1
          ui:
            enabled: true
            replicas: 1
            ingress:
              enabled: false
          metrics:
            enabled:
              - dns:query
              - drop
              - tcp
              - flow
              - icmp
              - http
            serviceMonitor:
              enabled: false
            dashboards:
              enabled: false

        # Gateway API
        gatewayAPI:
          enabled: true

        # IPv4/IPv6
        ipv4:
          enabled: true
        ipv6:
          enabled: false

        # Operator
        operator:
          replicas: 1
          prometheus:
            enabled: false

        # Prometheus
        prometheus:
          enabled: false

        # CNI
        cni:
          install: true
          exclusive: true
          chainingMode: none
          customConf: false

        # Bandwidth Manager
        bandwidthManager:
          enabled: true
          bbr: true

        # Host firewall
        hostFirewall:
          enabled: true

        # Encryption
        encryption:
          enabled: false
          type: wireguard

        # Local Redirect Policy
        localRedirectPolicy: true

        # KubeVirt support
        hostPort:
          enabled: true

        # Security
        policyEnforcementMode: default

        # Resources
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 512Mi

        # Node selector
        nodeSelector:
          kubernetes.io/os: linux

        # Tolerations
        tolerations:
          - operator: Exists

        # PDB
        pdb:
          enabled: false

        # Rollout
        rolloutMaxUnavailable: 1
        rollOutCiliumPods: true

        # Debug
        debug:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true        # Use Server-Side Apply for adoption
      - RespectIgnoreDifferences=true  # Respect ignoreDifferences (no forced sync)
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences to prevent unnecessary updates
  # These fields may differ between inline-deployed and ArgoCD-managed resources
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/metadata/annotations/container.apparmor.security.beta.kubernetes.io~1cilium-agent
        - /spec/template/metadata/annotations
        - /metadata/labels/app.kubernetes.io~1managed-by
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /metadata/annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
        - /metadata/labels/app.kubernetes.io~1managed-by
